# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: image_detection.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='image_detection.proto',
  package='ObjDet.Grpc',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x15image_detection.proto\x12\x0bObjDet.Grpc\"\x1a\n\x18\x44\x65tectableObjectsRequest\"5\n\x19\x44\x65tectableObjectsResponse\x12\x18\n\x10\x61vailable_object\x18\x01 \x03(\t\"&\n\x15ImageDetectionRequest\x12\r\n\x05image\x18\x01 \x01(\x0c\"{\n\tDetection\x12\x13\n\x0bobject_name\x18\x01 \x01(\t\x12\x12\n\nconfidence\x18\x03 \x01(\x02\x12\x12\n\ntop_left_x\x18\x05 \x01(\x05\x12\x12\n\ntop_left_y\x18\x07 \x01(\x05\x12\r\n\x05width\x18\t \x01(\x05\x12\x0e\n\x06height\x18\x0b \x01(\x05\"D\n\x16ImageDetectionResponse\x12*\n\ndetections\x18\x01 \x03(\x0b\x32\x16.ObjDet.Grpc.Detection2\xba\x02\n\x0eImageDetection\x12g\n\x14GetDetectableObjects\x12%.ObjDet.Grpc.DetectableObjectsRequest\x1a&.ObjDet.Grpc.DetectableObjectsResponse\"\x00\x12X\n\x0b\x44\x65tectImage\x12\".ObjDet.Grpc.ImageDetectionRequest\x1a#.ObjDet.Grpc.ImageDetectionResponse\"\x00\x12\x65\n\x14\x44\x65tectMultipleImages\x12\".ObjDet.Grpc.ImageDetectionRequest\x1a#.ObjDet.Grpc.ImageDetectionResponse\"\x00(\x01\x30\x01\x62\x06proto3'
)




_DETECTABLEOBJECTSREQUEST = _descriptor.Descriptor(
  name='DetectableObjectsRequest',
  full_name='ObjDet.Grpc.DetectableObjectsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=38,
  serialized_end=64,
)


_DETECTABLEOBJECTSRESPONSE = _descriptor.Descriptor(
  name='DetectableObjectsResponse',
  full_name='ObjDet.Grpc.DetectableObjectsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='available_object', full_name='ObjDet.Grpc.DetectableObjectsResponse.available_object', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=66,
  serialized_end=119,
)


_IMAGEDETECTIONREQUEST = _descriptor.Descriptor(
  name='ImageDetectionRequest',
  full_name='ObjDet.Grpc.ImageDetectionRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='image', full_name='ObjDet.Grpc.ImageDetectionRequest.image', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=121,
  serialized_end=159,
)


_DETECTION = _descriptor.Descriptor(
  name='Detection',
  full_name='ObjDet.Grpc.Detection',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='object_name', full_name='ObjDet.Grpc.Detection.object_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='confidence', full_name='ObjDet.Grpc.Detection.confidence', index=1,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='top_left_x', full_name='ObjDet.Grpc.Detection.top_left_x', index=2,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='top_left_y', full_name='ObjDet.Grpc.Detection.top_left_y', index=3,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='width', full_name='ObjDet.Grpc.Detection.width', index=4,
      number=9, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='height', full_name='ObjDet.Grpc.Detection.height', index=5,
      number=11, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=161,
  serialized_end=284,
)


_IMAGEDETECTIONRESPONSE = _descriptor.Descriptor(
  name='ImageDetectionResponse',
  full_name='ObjDet.Grpc.ImageDetectionResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='detections', full_name='ObjDet.Grpc.ImageDetectionResponse.detections', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=286,
  serialized_end=354,
)

_IMAGEDETECTIONRESPONSE.fields_by_name['detections'].message_type = _DETECTION
DESCRIPTOR.message_types_by_name['DetectableObjectsRequest'] = _DETECTABLEOBJECTSREQUEST
DESCRIPTOR.message_types_by_name['DetectableObjectsResponse'] = _DETECTABLEOBJECTSRESPONSE
DESCRIPTOR.message_types_by_name['ImageDetectionRequest'] = _IMAGEDETECTIONREQUEST
DESCRIPTOR.message_types_by_name['Detection'] = _DETECTION
DESCRIPTOR.message_types_by_name['ImageDetectionResponse'] = _IMAGEDETECTIONRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DetectableObjectsRequest = _reflection.GeneratedProtocolMessageType('DetectableObjectsRequest', (_message.Message,), {
  'DESCRIPTOR' : _DETECTABLEOBJECTSREQUEST,
  '__module__' : 'image_detection_pb2'
  # @@protoc_insertion_point(class_scope:ObjDet.Grpc.DetectableObjectsRequest)
  })
_sym_db.RegisterMessage(DetectableObjectsRequest)

DetectableObjectsResponse = _reflection.GeneratedProtocolMessageType('DetectableObjectsResponse', (_message.Message,), {
  'DESCRIPTOR' : _DETECTABLEOBJECTSRESPONSE,
  '__module__' : 'image_detection_pb2'
  # @@protoc_insertion_point(class_scope:ObjDet.Grpc.DetectableObjectsResponse)
  })
_sym_db.RegisterMessage(DetectableObjectsResponse)

ImageDetectionRequest = _reflection.GeneratedProtocolMessageType('ImageDetectionRequest', (_message.Message,), {
  'DESCRIPTOR' : _IMAGEDETECTIONREQUEST,
  '__module__' : 'image_detection_pb2'
  # @@protoc_insertion_point(class_scope:ObjDet.Grpc.ImageDetectionRequest)
  })
_sym_db.RegisterMessage(ImageDetectionRequest)

Detection = _reflection.GeneratedProtocolMessageType('Detection', (_message.Message,), {
  'DESCRIPTOR' : _DETECTION,
  '__module__' : 'image_detection_pb2'
  # @@protoc_insertion_point(class_scope:ObjDet.Grpc.Detection)
  })
_sym_db.RegisterMessage(Detection)

ImageDetectionResponse = _reflection.GeneratedProtocolMessageType('ImageDetectionResponse', (_message.Message,), {
  'DESCRIPTOR' : _IMAGEDETECTIONRESPONSE,
  '__module__' : 'image_detection_pb2'
  # @@protoc_insertion_point(class_scope:ObjDet.Grpc.ImageDetectionResponse)
  })
_sym_db.RegisterMessage(ImageDetectionResponse)



_IMAGEDETECTION = _descriptor.ServiceDescriptor(
  name='ImageDetection',
  full_name='ObjDet.Grpc.ImageDetection',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=357,
  serialized_end=671,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetDetectableObjects',
    full_name='ObjDet.Grpc.ImageDetection.GetDetectableObjects',
    index=0,
    containing_service=None,
    input_type=_DETECTABLEOBJECTSREQUEST,
    output_type=_DETECTABLEOBJECTSRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='DetectImage',
    full_name='ObjDet.Grpc.ImageDetection.DetectImage',
    index=1,
    containing_service=None,
    input_type=_IMAGEDETECTIONREQUEST,
    output_type=_IMAGEDETECTIONRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='DetectMultipleImages',
    full_name='ObjDet.Grpc.ImageDetection.DetectMultipleImages',
    index=2,
    containing_service=None,
    input_type=_IMAGEDETECTIONREQUEST,
    output_type=_IMAGEDETECTIONRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_IMAGEDETECTION)

DESCRIPTOR.services_by_name['ImageDetection'] = _IMAGEDETECTION

# @@protoc_insertion_point(module_scope)
