# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: image_detection.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='image_detection.proto',
  package='ObjDet.Grpc',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x15image_detection.proto\x12\x0bObjDet.Grpc\"\x1b\n\x19\x41vailableDetectorsRequest\"E\n\x0c\x44\x65tectorInfo\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05model\x18\x03 \x01(\t\x12\x18\n\x10\x64\x65tected_objects\x18\x05 \x03(\t\"J\n\x1a\x41vailableDetectorsResponse\x12,\n\tdetectors\x18\x01 \x03(\x0b\x32\x19.ObjDet.Grpc.DetectorInfo\"&\n\x15ImageDetectionRequest\x12\r\n\x05image\x18\x01 \x01(\x0c\"{\n\tDetection\x12\x13\n\x0bobject_name\x18\x01 \x01(\t\x12\x12\n\nconfidence\x18\x03 \x01(\x02\x12\x12\n\ntop_left_x\x18\x05 \x01(\x05\x12\x12\n\ntop_left_y\x18\x07 \x01(\x05\x12\r\n\x05width\x18\t \x01(\x05\x12\x0e\n\x06height\x18\x0b \x01(\x05\"D\n\x16ImageDetectionResponse\x12*\n\ndetections\x18\x01 \x03(\x0b\x32\x16.ObjDet.Grpc.Detection2\xbe\x02\n\x0eImageDetection\x12k\n\x16ListAvailableDetectors\x12&.ObjDet.Grpc.AvailableDetectorsRequest\x1a\'.ObjDet.Grpc.AvailableDetectorsResponse\"\x00\x12X\n\x0b\x44\x65tectImage\x12\".ObjDet.Grpc.ImageDetectionRequest\x1a#.ObjDet.Grpc.ImageDetectionResponse\"\x00\x12\x65\n\x14\x44\x65tectMultipleImages\x12\".ObjDet.Grpc.ImageDetectionRequest\x1a#.ObjDet.Grpc.ImageDetectionResponse\"\x00(\x01\x30\x01\x62\x06proto3'
)




_AVAILABLEDETECTORSREQUEST = _descriptor.Descriptor(
  name='AvailableDetectorsRequest',
  full_name='ObjDet.Grpc.AvailableDetectorsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=38,
  serialized_end=65,
)


_DETECTORINFO = _descriptor.Descriptor(
  name='DetectorInfo',
  full_name='ObjDet.Grpc.DetectorInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='ObjDet.Grpc.DetectorInfo.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='model', full_name='ObjDet.Grpc.DetectorInfo.model', index=1,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='detected_objects', full_name='ObjDet.Grpc.DetectorInfo.detected_objects', index=2,
      number=5, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=67,
  serialized_end=136,
)


_AVAILABLEDETECTORSRESPONSE = _descriptor.Descriptor(
  name='AvailableDetectorsResponse',
  full_name='ObjDet.Grpc.AvailableDetectorsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='detectors', full_name='ObjDet.Grpc.AvailableDetectorsResponse.detectors', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=138,
  serialized_end=212,
)


_IMAGEDETECTIONREQUEST = _descriptor.Descriptor(
  name='ImageDetectionRequest',
  full_name='ObjDet.Grpc.ImageDetectionRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='image', full_name='ObjDet.Grpc.ImageDetectionRequest.image', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=214,
  serialized_end=252,
)


_DETECTION = _descriptor.Descriptor(
  name='Detection',
  full_name='ObjDet.Grpc.Detection',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='object_name', full_name='ObjDet.Grpc.Detection.object_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='confidence', full_name='ObjDet.Grpc.Detection.confidence', index=1,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='top_left_x', full_name='ObjDet.Grpc.Detection.top_left_x', index=2,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='top_left_y', full_name='ObjDet.Grpc.Detection.top_left_y', index=3,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='width', full_name='ObjDet.Grpc.Detection.width', index=4,
      number=9, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='height', full_name='ObjDet.Grpc.Detection.height', index=5,
      number=11, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=254,
  serialized_end=377,
)


_IMAGEDETECTIONRESPONSE = _descriptor.Descriptor(
  name='ImageDetectionResponse',
  full_name='ObjDet.Grpc.ImageDetectionResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='detections', full_name='ObjDet.Grpc.ImageDetectionResponse.detections', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=379,
  serialized_end=447,
)

_AVAILABLEDETECTORSRESPONSE.fields_by_name['detectors'].message_type = _DETECTORINFO
_IMAGEDETECTIONRESPONSE.fields_by_name['detections'].message_type = _DETECTION
DESCRIPTOR.message_types_by_name['AvailableDetectorsRequest'] = _AVAILABLEDETECTORSREQUEST
DESCRIPTOR.message_types_by_name['DetectorInfo'] = _DETECTORINFO
DESCRIPTOR.message_types_by_name['AvailableDetectorsResponse'] = _AVAILABLEDETECTORSRESPONSE
DESCRIPTOR.message_types_by_name['ImageDetectionRequest'] = _IMAGEDETECTIONREQUEST
DESCRIPTOR.message_types_by_name['Detection'] = _DETECTION
DESCRIPTOR.message_types_by_name['ImageDetectionResponse'] = _IMAGEDETECTIONRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AvailableDetectorsRequest = _reflection.GeneratedProtocolMessageType('AvailableDetectorsRequest', (_message.Message,), {
  'DESCRIPTOR' : _AVAILABLEDETECTORSREQUEST,
  '__module__' : 'image_detection_pb2'
  # @@protoc_insertion_point(class_scope:ObjDet.Grpc.AvailableDetectorsRequest)
  })
_sym_db.RegisterMessage(AvailableDetectorsRequest)

DetectorInfo = _reflection.GeneratedProtocolMessageType('DetectorInfo', (_message.Message,), {
  'DESCRIPTOR' : _DETECTORINFO,
  '__module__' : 'image_detection_pb2'
  # @@protoc_insertion_point(class_scope:ObjDet.Grpc.DetectorInfo)
  })
_sym_db.RegisterMessage(DetectorInfo)

AvailableDetectorsResponse = _reflection.GeneratedProtocolMessageType('AvailableDetectorsResponse', (_message.Message,), {
  'DESCRIPTOR' : _AVAILABLEDETECTORSRESPONSE,
  '__module__' : 'image_detection_pb2'
  # @@protoc_insertion_point(class_scope:ObjDet.Grpc.AvailableDetectorsResponse)
  })
_sym_db.RegisterMessage(AvailableDetectorsResponse)

ImageDetectionRequest = _reflection.GeneratedProtocolMessageType('ImageDetectionRequest', (_message.Message,), {
  'DESCRIPTOR' : _IMAGEDETECTIONREQUEST,
  '__module__' : 'image_detection_pb2'
  # @@protoc_insertion_point(class_scope:ObjDet.Grpc.ImageDetectionRequest)
  })
_sym_db.RegisterMessage(ImageDetectionRequest)

Detection = _reflection.GeneratedProtocolMessageType('Detection', (_message.Message,), {
  'DESCRIPTOR' : _DETECTION,
  '__module__' : 'image_detection_pb2'
  # @@protoc_insertion_point(class_scope:ObjDet.Grpc.Detection)
  })
_sym_db.RegisterMessage(Detection)

ImageDetectionResponse = _reflection.GeneratedProtocolMessageType('ImageDetectionResponse', (_message.Message,), {
  'DESCRIPTOR' : _IMAGEDETECTIONRESPONSE,
  '__module__' : 'image_detection_pb2'
  # @@protoc_insertion_point(class_scope:ObjDet.Grpc.ImageDetectionResponse)
  })
_sym_db.RegisterMessage(ImageDetectionResponse)



_IMAGEDETECTION = _descriptor.ServiceDescriptor(
  name='ImageDetection',
  full_name='ObjDet.Grpc.ImageDetection',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=450,
  serialized_end=768,
  methods=[
  _descriptor.MethodDescriptor(
    name='ListAvailableDetectors',
    full_name='ObjDet.Grpc.ImageDetection.ListAvailableDetectors',
    index=0,
    containing_service=None,
    input_type=_AVAILABLEDETECTORSREQUEST,
    output_type=_AVAILABLEDETECTORSRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='DetectImage',
    full_name='ObjDet.Grpc.ImageDetection.DetectImage',
    index=1,
    containing_service=None,
    input_type=_IMAGEDETECTIONREQUEST,
    output_type=_IMAGEDETECTIONRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='DetectMultipleImages',
    full_name='ObjDet.Grpc.ImageDetection.DetectMultipleImages',
    index=2,
    containing_service=None,
    input_type=_IMAGEDETECTIONREQUEST,
    output_type=_IMAGEDETECTIONRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_IMAGEDETECTION)

DESCRIPTOR.services_by_name['ImageDetection'] = _IMAGEDETECTION

# @@protoc_insertion_point(module_scope)
